# Generated by Django 4.1.7 on 2023-05-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_grouppost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPost',
        ),
    ]
