# Generated by Django 4.1.7 on 2023-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_group_group_type'),
        ('posts', '0003_delete_grouppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='accounts.account'),
        ),
    ]
