# Generated by Django 4.1.7 on 2023-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_group_group_type'),
        ('posts', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='SharePostView', to='accounts.account'),
        ),
    ]
