# Generated by Django 4.1.7 on 2023-05-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_sharepost_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='sharepost',
            old_name='type',
            new_name='post_type',
        ),
    ]
