# Generated by Django 4.1.7 on 2023-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
