# Generated by Django 4.1.7 on 2023-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_savedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedposts',
            name='post_id',
            field=models.TextField(null=True),
        ),
    ]
