# Generated by Django 4.2.2 on 2023-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_location_post_status_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Friends', 'Friends')], default='Public', max_length=8, null=True),
        ),
    ]
