# Generated by Django 4.2.2 on 2023-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_whoc_can_send_me_friend_request_account_who_can_send_me_friend_request'),
        ('posts', '0014_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepost',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Friends', 'Friends')], default='Public', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sharepost',
            name='tags',
            field=models.ManyToManyField(related_name='shared_tags', to='accounts.account'),
        ),
    ]
