# Generated by Django 4.2.2 on 2023-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_group_display_post_author_username_on_post'),
        ('posts', '0019_alter_post_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shared_tags', to='accounts.account'),
        ),
    ]
