# Generated by Django 4.2.2 on 2023-09-21 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelings',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
