# Generated by Django 4.2.2 on 2023-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_feelings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelings',
            name='feeling',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
