# Generated by Django 4.2.2 on 2023-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_date_feelings_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelings',
            name='post_type',
            field=models.TextField(choices=[('feeling_post', 'feeling_post')], null=True),
        ),
    ]
