# Generated by Django 4.2.2 on 2023-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_whoc_can_send_me_friend_request_account_who_can_send_me_friend_request'),
        ('mainApp', '0010_alter_feelings_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feelings',
            name='angry_reaction',
            field=models.ManyToManyField(blank=True, related_name='feelings_angry_reaction', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='feelings',
            name='haha_reaction',
            field=models.ManyToManyField(blank=True, related_name='feelings_haha_reaction', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='feelings',
            name='like_reaction',
            field=models.ManyToManyField(blank=True, related_name='feelings_like_reaction', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='feelings',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='feelings_likes', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='feelings',
            name='love_reaction',
            field=models.ManyToManyField(blank=True, related_name='feelings_love_reaction', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='feelings',
            name='sad_reaction',
            field=models.ManyToManyField(blank=True, related_name='feelings_sad_reaction', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='feelings',
            name='wow_reaction',
            field=models.ManyToManyField(blank=True, related_name='feelings_wow_reaction', to='accounts.account'),
        ),
    ]
