# Generated by Django 4.2.2 on 2023-09-23 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_whoc_can_send_me_friend_request_account_who_can_send_me_friend_request'),
        ('mainApp', '0011_feelings_angry_reaction_feelings_haha_reaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareFeelingsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.TextField(choices=[('sharedFeelingPost', 'sharedFeelingPost')], null=True)),
                ('caption', models.TextField(blank=True, max_length=1500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('angry_reaction', models.ManyToManyField(blank=True, related_name='shared_feeling_angry_reaction', to='accounts.account')),
                ('haha_reaction', models.ManyToManyField(blank=True, related_name='shared_feeling_post_haha_reaction', to='accounts.account')),
                ('like_reaction', models.ManyToManyField(blank=True, related_name='shared_feeling_post_like_reaction', to='accounts.account')),
                ('likes', models.ManyToManyField(blank=True, related_name='shared_feeling_post_likes', to='accounts.account')),
                ('love_reaction', models.ManyToManyField(blank=True, related_name='shared_feeling_post_love_reaction', to='accounts.account')),
                ('referer_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feelings_post', to='mainApp.feelings')),
                ('sad_reaction', models.ManyToManyField(blank=True, related_name='shared_feeling_post_sad_reaction', to='accounts.account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('views', models.ManyToManyField(blank=True, related_name='ShareFeelingView', to='accounts.account')),
                ('wow_reaction', models.ManyToManyField(blank=True, related_name='shared_feeling_post_wow_reaction', to='accounts.account')),
            ],
        ),
    ]
