# Generated by Django 4.2.2 on 2023-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='user_agent',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
