# Generated by Django 4.2.2 on 2023-11-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_delete_helptext_delete_helptitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='user_logged_in',
            new_name='account_logged_in',
        ),
    ]
