# Generated by Django 4.2.2 on 2023-11-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_group_blue_tick'),
        ('mainApp', '0019_rename_user_logged_in_logs_account_logged_in'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='loggin_Logs',
        ),
    ]
