# Generated by Django 4.2.2 on 2023-11-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='account',
            new_name='user',
        ),
    ]
