# Generated by Django 4.1.7 on 2023-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentmixin_grouppostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppostcomment',
            name='type',
            field=models.CharField(choices=[('GroupPostComment', 'GroupPostComment')], max_length=20, null=True),
        ),
    ]
