# Generated by Django 4.1.7 on 2023-05-10 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_groupsharepost_group'),
        ('comments', '0003_grouppostcomment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSharedPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('GroupSharedPostComment', 'GroupSharedPostComment')], max_length=25, null=True)),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_shared_post_comments', to='accounts.groupsharepost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='grouppostcomment',
            name='commentmixin_ptr',
        ),
        migrations.RemoveField(
            model_name='grouppostcomment',
            name='post_id',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sharedpostcomment',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('comment', 'comment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sharedpostcomment',
            name='type',
            field=models.CharField(choices=[('sharePcomment', 'sharePcomment')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='CommentMixin',
        ),
        migrations.DeleteModel(
            name='GroupPostComment',
        ),
    ]
