# Generated by Django 4.1.7 on 2023-05-10 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_groupsharepost_group'),
        ('comments', '0004_groupsharedpostcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPostComment',
            fields=[
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('GroupPostComment', 'GroupPostComment')], max_length=20, null=True)),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comments', to='accounts.grouppost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
