# Generated by Django 4.1.7 on 2023-05-10 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_grouppostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsharedpostcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
