# Generated by Django 4.1.7 on 2023-05-12 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_account_friends'),
        ('comments', '0006_alter_groupsharedpostcomment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharePostCommentReply',
            new_name='SharedPostCommentReply',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='type',
            new_name='type_of_comment',
        ),
        migrations.RenameField(
            model_name='grouppostcomment',
            old_name='type',
            new_name='type_of_comment',
        ),
        migrations.RenameField(
            model_name='groupsharedpostcomment',
            old_name='type',
            new_name='type_of_comment',
        ),
        migrations.RenameField(
            model_name='sharedpostcomment',
            old_name='type',
            new_name='type_of_comment',
        ),
        migrations.CreateModel(
            name='SharedGroupPostCommentReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parrent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shared_post_comment_reply', to='comments.groupsharedpostcomment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='GroupPostCommentReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parrent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comment_reply', to='comments.grouppostcomment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
