# Generated by Django 4.1.7 on 2023-05-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_friendrequest'),
        ('posts', '0009_alter_sharepost_id'),
        ('comments', '0007_rename_sharepostcommentreply_sharedpostcommentreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppostcommentreply',
            name='parrent_comment',
        ),
        migrations.RemoveField(
            model_name='grouppostcommentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupsharedpostcomment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='groupsharedpostcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedgrouppostcommentreply',
            name='parrent_comment',
        ),
        migrations.RemoveField(
            model_name='sharedgrouppostcommentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedpostcomment',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='sharedpostcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedpostcommentreply',
            name='parrent_comment',
        ),
        migrations.RemoveField(
            model_name='sharedpostcommentreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('SharedPostComment', 'SharedPostComment'), ('GroupSharedPostComment', 'GroupSharedPostComment'), ('GroupPostComment', 'GroupPostComment')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='group_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comment', to='accounts.grouppost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='group_shared_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_shared_post', to='accounts.groupsharepost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='share_post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_post_comments', to='posts.sharepost'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_type',
            field=models.CharField(choices=[('SharedPostCommentReply', 'SharedPostCommentReply'), ('GroupPostCommentReply', 'GroupPostCommentReply'), ('SharedGroupPostCommentReply', 'SharedGroupPostCommentReply')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='GroupPostComment',
        ),
        migrations.DeleteModel(
            name='GroupPostCommentReply',
        ),
        migrations.DeleteModel(
            name='GroupSharedPostComment',
        ),
        migrations.DeleteModel(
            name='SharedGroupPostCommentReply',
        ),
        migrations.DeleteModel(
            name='SharedPostComment',
        ),
        migrations.DeleteModel(
            name='SharedPostCommentReply',
        ),
    ]
