# Generated by Django 4.1.7 on 2023-05-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_remove_grouppostcommentreply_parrent_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('PostComment', 'PostComment'), ('SharedPostComment', 'SharedPostComment'), ('GroupSharedPostComment', 'GroupSharedPostComment'), ('GroupPostComment', 'GroupPostComment')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type_of_comment',
            field=models.CharField(choices=[('PostComment', 'PostComment'), ('SharedPostComment', 'SharedPostComment'), ('GroupSharedPostComment', 'GroupSharedPostComment'), ('GroupPostComment', 'GroupPostComment')], max_length=30, null=True),
        ),
    ]
