# Generated by Django 4.1.7 on 2023-05-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_comment_comment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_type',
        ),
    ]
