# Generated by Django 4.1.7 on 2023-05-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_friendrequest'),
        ('posts', '0009_alter_sharepost_id'),
        ('comments', '0010_remove_comment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='group_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_post_comment', to='accounts.grouppost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='group_shared_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_shared_post', to='accounts.groupsharepost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='share_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_post_comments', to='posts.sharepost'),
        ),
    ]
