# Generated by Django 4.1.7 on 2023-06-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_account_bio'),
        ('comments', '0012_alter_commentreply_reply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='commlikes', to='accounts.account'),
        ),
    ]
