# Generated by Django 4.1.7 on 2023-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_account_bio'),
        ('comments', '0013_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='likes',
            field=models.ManyToManyField(related_name='replylikes', to='accounts.account'),
        ),
    ]
