# Generated by Django 4.2.2 on 2023-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0015_comment_feeling_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type_of_comment',
            field=models.CharField(choices=[('PostComment', 'PostComment'), ('SharedPostComment', 'SharedPostComment'), ('GroupSharedPostComment', 'GroupSharedPostComment'), ('GroupPostComment', 'GroupPostComment'), ('FeelingPostComment', 'FeelingPostComment')], max_length=30, null=True),
        ),
    ]
