# Generated by Django 4.2.2 on 2023-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0016_alter_comment_type_of_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type_of_comment',
            field=models.CharField(choices=[('PostComment', 'PostComment'), ('SharedPostComment', 'SharedPostComment'), ('GroupSharedPostComment', 'GroupSharedPostComment'), ('GroupPostComment', 'GroupPostComment'), ('FeelingPostComment', 'FeelingPostComment'), ('FeelingSharedPostComment', 'FeelingSharedPostComment')], max_length=30, null=True),
        ),
    ]
