# Generated by Django 4.2.2 on 2023-09-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_sharefeelingsposts'),
        ('comments', '0017_alter_comment_type_of_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='feeling_shared_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeling_share_post', to='mainApp.sharefeelingsposts'),
        ),
    ]
