# Generated by Django 4.2.2 on 2023-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_comment_feeling_shared_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='reply_type',
            field=models.CharField(choices=[('PostCommentsReply', 'PostCommentsReply'), ('SharedPostCommentReply', 'SharedPostCommentReply'), ('GroupPostCommentReply', 'GroupPostCommentReply'), ('SharedGroupPostCommentReply', 'SharedGroupPostCommentReply'), ('FeelingPostCommentReply', 'FeelingPostCommentReply')], max_length=30, null=True),
        ),
    ]
