# Generated by Django 4.2.2 on 2023-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0020_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='reason',
            field=models.CharField(choices=[('Nudity', 'Nudity'), ('Violence', 'Violence'), ('Harassment', 'Harassment'), ('Suicide or Self-injury', 'Suicide or Self-injury'), ('Spam', 'Spam'), ('Unauthorized Sales', 'Unauthorized Sales'), ('Hate Speech', 'Hate Speech'), ('Terrorism', 'Terrorism'), ('Something Else', 'Something Else')], default='Nudity', max_length=50),
        ),
    ]
