# Generated by Django 4.2.2 on 2023-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
