# Generated by Django 4.2.2 on 2023-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_sell_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='image',
            field=models.ImageField(default='1', upload_to='sell'),
            preserve_default=False,
        ),
    ]
