# Generated by Django 4.2.2 on 2023-08-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_sell_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='category',
            field=models.CharField(choices=[('Apperal & Accessories', 'Apperal & Accessories'), ('Arts & Entertainment', 'Arts & Entertainment'), ('Food & Beverages', 'Food & Beverages'), ('Furniture', 'Furniture'), ('Business & Industrial Products', 'Business & Industrial Products'), ("Camera & equipment's", "Camera & equipment's"), ('Home & Garden', 'Home & Garden'), ('Luggage & Bags', 'Luggage & Bags'), ('Toys and Games', 'Toys and Games'), ('Vehicles & Spare Parts', 'Vehicles & Spare Parts'), ('Software & Hardware', 'Software & Hardware'), ('Sporting goods', 'Sporting goods'), ('Baby Products', 'Baby Products'), ('Electronics', 'Electronics'), ('Health & Beauty Products', 'Health & Beauty Products'), ('Office Supplies', 'Office Supplies')], max_length=40, null=True),
        ),
    ]
