# Generated by Django 4.2.2 on 2023-08-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_sell_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
