# Generated by Django 4.2.2 on 2023-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_account_who_can_see_my_posts'),
        ('marketplace', '0006_sell_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='total_views',
            field=models.ManyToManyField(related_name='total_views', to='accounts.account'),
        ),
    ]
