# Generated by Django 4.2.2 on 2023-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_sell_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='total_views',
        ),
        migrations.AddField(
            model_name='sell',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
