# Generated by Django 4.2.2 on 2023-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_group_who_can_post'),
        ('marketplace', '0009_remove_sell_total_views_sell_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='total_views',
            field=models.ManyToManyField(blank=True, related_name='total_views', to='accounts.account'),
        ),
    ]
