# Generated by Django 4.1.7 on 2023-05-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='date_send',
        ),
    ]
