# Generated by Django 4.2.2 on 2023-07-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_grouprules'),
        ('chat', '0003_alter_message_from_user_alter_message_to_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomGroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroomgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
