# Generated by Django 4.2.2 on 2023-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroomgroup_chatroomgroupmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomgroup',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
