# Generated by Django 4.2.2 on 2023-08-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_account_theme'),
        ('chat', '0005_alter_chatroomgroup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomgroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='chatroomgroup',
            name='members',
            field=models.ManyToManyField(related_name='memsbers', to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='ChatRoomGroupMessages',
        ),
    ]
