# Generated by Django 4.2.2 on 2023-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroomgroup_admin_alter_chatroomgroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomgroup',
            name='icon',
            field=models.ImageField(default='default_cover.png', upload_to='group_chat_covers'),
        ),
    ]
