# Generated by Django 4.2.2 on 2023-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_privatechat_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='seen',
            new_name='user_1_seen',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user_2_seen',
            field=models.BooleanField(default=False),
        ),
    ]
