# Generated by Django 4.2.2 on 2023-10-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='chat.chatroomgroup'),
        ),
    ]
