# Generated by Django 4.2.2 on 2023-11-19 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_groupmessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomgroup',
            name='last_contact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='last_contact',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
