# Generated by Django 4.2.2 on 2023-09-13 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_delete_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 13, 13, 46, 21, 821980, tzinfo=datetime.timezone.utc)),
        ),
    ]
