# Generated by Django 4.2.2 on 2023-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_account_who_can_see_my_friends_list'),
        ('stories', '0004_alter_story_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.ManyToManyField(related_name='story_views', to='accounts.account'),
        ),
    ]
