# Generated by Django 4.2.2 on 2023-09-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
    ]
