# Generated by Django 4.1.7 on 2023-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_description_group_group_cover_group_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='group',
            name='memebers',
            field=models.ManyToManyField(related_name='members', to='accounts.account'),
        ),
    ]
