# Generated by Django 4.1.7 on 2023-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_group_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.TextField(choices=[('General', 'General'), ('Buy and Sell', 'Buy and Sell'), ('Gaming', 'Gaming'), ('Job', 'Job'), ('Parenting', 'Parenting')], max_length=15, null=True),
        ),
    ]
