# Generated by Django 4.1.7 on 2023-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_group_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='rule_description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='rule_title',
        ),
        migrations.AlterField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], max_length=7, null=True),
        ),
    ]
