# Generated by Django 4.1.7 on 2023-05-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_group_rule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
