# Generated by Django 4.1.7 on 2023-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_grouppost_options_grouppost_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsharepost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
