# Generated by Django 4.1.7 on 2023-05-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsharepost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SharePosts', to='accounts.group'),
        ),
    ]
