# Generated by Django 4.1.7 on 2023-05-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppost',
            old_name='type',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='groupsharepost',
            old_name='type',
            new_name='post_type',
        ),
    ]
