# Generated by Django 4.1.7 on 2023-05-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsharepost',
            name='group',
        ),
    ]
