# Generated by Django 4.1.7 on 2023-05-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_groupsharepost_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
