# Generated by Django 4.1.7 on 2023-06-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='caption',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
