# Generated by Django 4.1.7 on 2023-06-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_groupvisitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_title', models.CharField(max_length=500)),
                ('rule_body', models.TextField(max_length=5000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
    ]
