# Generated by Django 4.2.2 on 2023-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_grouprules'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.BooleanField(default=True),
        ),
    ]
