# Generated by Django 4.2.2 on 2023-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], max_length=7, null=True),
        ),
    ]
