# Generated by Django 4.2.1 on 2023-08-13 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_group_privacy_alter_group_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReportText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_text', to='accounts.reporttitle')),
            ],
        ),
    ]
