# Generated by Django 4.2.2 on 2023-08-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_reporttext_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.TextField(choices=[('Hate speech', 'Hate speech'), ('Nudity or sexual content', 'Nudity or sexual content'), ('Violence', 'Violence'), ('Harassment', 'Harassment'), ('Scams and fake Groups', 'Scams and fake Groups'), ('Unauthorised sales', 'Unauthorised sales'), ('intellectual property', 'intellectual property')], max_length=35, null=True)),
                ('problem', models.TextField(choices=[('Asking for financial information', 'Asking for financial information'), ('Pretending to be another business', 'Pretending to be another business'), ('Pretending to be another person', 'Pretending to be another person'), ('Fake Groups', 'Fake Groups'), ('Misleading Group name change', 'Misleading Group name change')], max_length=35, null=True)),
                ('text', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('who_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
