# Generated by Django 4.2.2 on 2023-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_report_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='problem',
            field=models.TextField(blank=True, choices=[('Asking for financial information', 'Asking for financial information'), ('Pretending to be another business', 'Pretending to be another business'), ('Pretending to be another person', 'Pretending to be another person'), ('Fake Groups', 'Fake Groups'), ('Misleading Group name change', 'Misleading Group name change')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
