# Generated by Django 4.2.1 on 2023-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_report_problem_alter_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='from_country',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
