# Generated by Django 4.2.2 on 2023-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_account_who_can_see_my_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='who_can_see_my_posts',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('Only me', 'Only me')], default='Public', max_length=10, null=True),
        ),
    ]
