# Generated by Django 4.2.2 on 2023-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_account_who_can_see_my_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='who_can_see_my_friends_list',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Friends', 'Friends'), ('Only Me', 'Only Me')], default='Everyone', max_length=10, null=True),
        ),
    ]
