# Generated by Django 4.2.2 on 2023-09-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_account_whoc_can_send_me_friend_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='whoc_can_send_me_friend_request',
            new_name='who_can_send_me_friend_request',
        ),
    ]
