# Generated by Django 4.2.2 on 2023-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_whoc_can_send_me_friend_request_account_who_can_send_me_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='who_can_see_my_email_address',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Friends', 'Friends'), ('Only Me', 'Only Me')], default='Everyone', max_length=10, null=True),
        ),
    ]
