# Generated by Django 4.2.2 on 2023-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_account_who_can_see_my_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_cover',
            field=models.ImageField(default='background_images/default_cover.png', upload_to='group_covers'),
        ),
    ]
