# Generated by Django 4.2.2 on 2023-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_group_group_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_cover',
            field=models.ImageField(default='default_cover.png', upload_to='group_covers'),
        ),
    ]
