# Generated by Django 4.2.2 on 2023-11-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_group_group_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportText',
        ),
        migrations.DeleteModel(
            name='ReportTitle',
        ),
    ]
