# Generated by Django 4.2.2 on 2023-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_delete_reporttext_delete_reporttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='who_can_post',
            field=models.CharField(choices=[('Only Admins', 'Only Admins'), ('Everyone', 'Everyone')], default='Everyone', max_length=15),
        ),
    ]
