# Generated by Django 4.2.2 on 2023-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_group_who_can_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.TextField(choices=[('General', 'General'), ('Buy and Sell', 'Buy and Sell'), ('Gaming', 'Gaming'), ('Job', 'Job'), ('Parenting', 'Parenting'), ('News', 'News')], max_length=15, null=True),
        ),
    ]
