# Generated by Django 4.2.2 on 2023-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_group_display_post_author_username_on_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='blue_tick',
            field=models.BooleanField(default=False),
        ),
    ]
