# Generated by Django 4.2.2 on 2023-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_group_blue_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blue_tick',
            field=models.BooleanField(default=False),
        ),
    ]
