# Generated by Django 4.2.2 on 2023-09-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0014_commentreply_likes'),
        ('accounts', '0043_alter_account_who_can_see_my_posts'),
        ('notifications', '0002_commentnotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCommentNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('repylied_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.commentreply')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
