# Generated by Django 4.2.2 on 2023-09-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_replycommentnotifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentnotifications',
            old_name='comment',
            new_name='post_comment',
        ),
    ]
