# Generated by Django 4.2.2 on 2023-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_sharedpostnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentnotifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postnotifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replycommentnotifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedpostnotifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
