# Generated by Django 4.2.2 on 2023-10-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_whoc_can_send_me_friend_request_account_who_can_send_me_friend_request'),
        ('notifications', '0006_commentnotifications_seen_postnotifications_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInviteNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('group_to_invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to='accounts.account')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender', to='accounts.account')),
            ],
        ),
    ]
